<?php

namespace AppBundle\Repository;

/**
 * ContributionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionsRepository extends \Doctrine\ORM\EntityRepository
{
}
