<?php

namespace AppBundle\Repository;

/**
 * Hara_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Hara_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
