<?php

namespace AppBundle\Repository;

/**
 * HaraCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HaraCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
